# Generated by Django 4.0.4 on 2022-10-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_ip_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=1200),
        ),
        migrations.AddField(
            model_name='post',
            name='rate',
            field=models.ManyToManyField(blank=True, related_name='post_rate', to='post.rate'),
        ),
    ]
