# Generated by Django 4.0.4 on 2022-10-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rate_alter_post_description_post_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rate',
        ),
        migrations.AddField(
            model_name='post',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
