# Generated by Django 4.0.4 on 2022-11-11 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rate',
        ),
        migrations.AddField(
            model_name='post',
            name='rates',
            field=models.ManyToManyField(blank=True, default=None, related_name='rate', to=settings.AUTH_USER_MODEL, verbose_name='Рейтинг'),
        ),
    ]
