# Generated by Django 4.0.4 on 2022-11-11 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0007_remove_post_rate_post_rates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rates',
        ),
        migrations.AddField(
            model_name='post',
            name='rates_minus',
            field=models.ManyToManyField(blank=True, default=None, related_name='rate_minus', to=settings.AUTH_USER_MODEL, verbose_name='Рейтинг минус'),
        ),
        migrations.AddField(
            model_name='post',
            name='rates_plus',
            field=models.ManyToManyField(blank=True, default=None, related_name='rate_plus', to=settings.AUTH_USER_MODEL, verbose_name='Рейтинг плюс'),
        ),
    ]
