# Generated by Django 4.0.4 on 2022-11-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_post_rates_post_rates_minus_post_rates_plus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='photo.jpg', null=True, upload_to='profile_images'),
        ),
    ]
