# Generated by Django 4.0.4 on 2022-12-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='git_href',
            field=models.URLField(blank=True, null=True),
        ),
    ]
